export const DUMMY_PROJECTS = [
  {
    id: 1,
    images: [
      '/images/landpage/project-1-part-1.jpg',
      '/images/landpage/project-1-part-2.jpg',
      '/images/landpage/project-1-part-3.jpg',
      '/images/landpage/project-1-part-4.jpg',
      '/images/landpage/project-1-part-5.jpg',
      '/images/landpage/project-1-part-6.jpg',
    ],
    status: 'SELLING',
    isTop: true,
    title: 'Vinhomes Grand Park',
    timeExprired: '1 năm', // infoPart Thời gian đầu tư
    profit: 15, // infoPart Lợi nhuận kỳ vọng
    investors: 0,
    amount: 0,
    pricePerPart: 6794300,
    total: 1000,
    position: 'Quận 9, Tp.Hồ Chí Minh',
    infoPartA: [
      { label: 'Diện tích sử dụng nhà ở:', value: '91,9 m²' },
      { label: 'Mục đích sử dụng:', value: 'Căn hộ chung cư' },
      { label: 'Pháp lý:', value: 'Sổ hồng chính chủ' },
      { label: 'Thời gian đầu tư:', value: '1 năm' },
    ],
    infoPartB: [
      { label: 'Lợi nhuận kỳ vọng:', value: '15%' },
      { label: 'Thời hạn sở hữu:', value: 'Lâu dài' },
      { label: 'Hình thức sử dụng:', value: 'Sử dụng riêng' },
    ],
    description: [
      'Khoảng 20 phút từ khu đô thị Vinhomes Central Park và cầu Thủ Thiêm Quận 2 có thể kết nối nhanh chóng đến Vinhome Quận 9.',
      'Đồng thời, trong tương lai Vành Đai 3 sẽ là tuyến đường huyết mạch chính kết nối dự án Vinhomes Quận 9 với khu vực trung tâm thành phố.',
      'Khu đô thị Vinhomes Grand Park được tập đoàn Vingroup phát triển theo mô hình thành phố thu nhỏ khép kín với hệ sinh thái tiện ích đa dạng, đồng bộ với tiêu chí “ALL IN ONE” đáp ứng cuộc sống trọn vẹn.',
      'Được bình chọn đánh giá là một trong những nơi đáng sống nhất tại Việt Nam, không chỉ mang đến không gian sống trong lành chất lượng với những trải nghiệm tiện ích mới chỉ có tại dự án Vinhomes Grand Park Quận 9.',
      'Mà còn làm “tăng nhiệt” thị trường bất động sản khu Đông TPHCM, mở ra cơ hội đầu tư vô cùng hấp dẫn khi dự án hoàn thiện.',
    ],
    video: 'TRq-khTzUXI',
    map: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.6519673929965!2d106.82803791480119!3d10.83792369227977!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317521594c233c59%3A0xce9a939da6465ada!2sVinhomes%20Grand%20Park!5e0!3m2!1svi!2s!4v1637740431260!5m2!1svi!2s',
  },
  {
    id: 4,
    images: [
      '/images/landpage/project-2-part-1.jpg',
      '/images/landpage/project-2-part-2.jpg',
      '/images/landpage/project-2-part-3.jpg',
      '/images/landpage/project-2-part-4.jpg',
      '/images/landpage/project-2-part-5.jpg',
    ],
    status: 'SELLING',
    isTop: true,
    title: 'Moonlight Centre Point',
    timeExprired: '6 tháng',
    profit: 15,
    investors: 0,
    amount: 0,
    total: 1000,
    position: 'Quận Bình Tân, TP.HCM',
    description: [
      'Kế thừa thành công và viết tiếp câu chuyện an cư qua chuỗi dự án mang thương hiệu Moonlight, Moonlight Centre Point là sản phẩm căn hộ mới nhất của Nhà phát triển dự án Hưng Thịnh Land tại tâm điểm khu Tên Lửa, như làn gió mới mang đến phồn vinh, giúp bạn thỏa mong ước an cư lạc nghiệp.',
      'Vươn mình kiêu hãnh ngay cung đường Tên Lửa sầm uất (lộ giới 40m), cách khu Chợ Lớn chưa đến 10 phút di chuyển, là vị trí kết nối toàn diện về trung tâm thành phố cũng như lan tỏa đi các tỉnh miền Tây Nam Bộ.',
      ' Đặc biệt, nơi đây còn được ví như “Phú Mỹ Hưng của khu Tây” với quy hoạch chỉn chu, hạ tầng giao thông phát triển và không gian sống trong lành, an ninh.',
      'Tọa lạc tại tâm điểm khu Tên Lửa, Moonlight Centre Point cũng hưởng lợi từ các dự án giao thông nghìn tỷ như: tuyến Metro 3A, Metro số 6, Vành Đai Trong cùng các tuyến đường huyết mạch: Quốc lộ 1A, Võ Văn Kiệt, Kinh Dương Vương, Hồng Bàng.',
      'Những công trình này không chỉ tạo ra diện mạo đô thị hiện đại, giúp kết nối thông suốt đến các khu vực mà còn góp phần tăng giá trị của Moonlight Centre Point khi quỹ đất nội đô đang ngày càng khan hiếm.',
    ],
    video: 'H5M32j0Wq3M',
    map: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.9175804631072!2d106.61142291516913!3d10.740835492345663!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f12ad498e93%3A0x443c121080239ca3!2sMOONLIGHT%20CENTRE%20POINT!5e0!3m2!1svi!2s!4v1637741444934!5m2!1svi!2s',
  },
  {
    id: 5,
    images: [
      '/images/landpage/project-3-part-1.jpg',
      '/images/landpage/project-3-part-2.jpg',
      '/images/landpage/project-3-part-3.jpg',
      '/images/landpage/project-3-part-4.jpg',
      '/images/landpage/project-3-part-5.jpg',
    ],
    status: 'SELLING',
    title: 'Bien Hoa Universe Complex',
    timeExprired: '6 tháng',
    profit: 15,
    investors: 0,
    amount: 0,
    total: 1000,
    position: 'Quận Bình Tân, TP.HCM',
    description: [
      'Bien Hoa Universe Complex tọa lạc ngay “trái tim” Biên Hòa - một trong những thành phố có tốc độ phát triển nhanh nhất, nơi cư dân dễ dàng thừa hưởng trọn vẹn nhịp sống sôi động của trung tâm sầm uất bậc nhất Đồng Nai.',
      'Đồng thời, dự án còn sở hữu vị trí đắt giá khi là tâm điểm kết nối các trục giao thông huyết mạch giữ vai trò quan trọng trong liên kết vùng Trung Bộ, Tây Nguyên với vùng kinh tế trọng điểm phía Nam.',
      'Đáp ứng đa dạng nhu cầu của cư dân, Bien Hoa Universe Complex cũng chính là nơi kết nối hoàn hảo với hệ thống tiện ích hiện hữu của một khu trung tâm kinh tế, chính trị, văn hóa, xã hội của tỉnh… chỉ trong tích tắc.',
      'Nhằm mang đến cuộc sống hiện đại, tiện nghi và thoải mái nhất cho cộng đồng trí thức thành đạt, chuỗi tiện ích nội khu của Bien Hoa Universe Complex được đầu tư một cách bài bản, đáp ứng những tiêu chuẩn khắt khe nhất. Dự án tiên phong phát triển căn hộ kết hợp khu thương mại, dịch vụ nhộn nhịp, sầm uất.',
      'Bien Hoa Universe Complex là sản phẩm tổng hòa của sự bài bản trong đầu tư, chỉn chu trong thiết kế, sự thấu hiểu nhu cầu của mỗi khách hàng. Và một yếu tố quan trọng góp phần làm trọn vẹn thêm giá trị của sản phẩm chính là cộng đồng cư dân trí thức và thành đạt tại TP.Biên Hòa.',
    ],
    video: 'H5M32j0Wq3M',
    map: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.9175804631072!2d106.61142291516913!3d10.740835492345663!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f12ad498e93%3A0x443c121080239ca3!2sMOONLIGHT%20CENTRE%20POINT!5e0!3m2!1svi!2s!4v1637741444934!5m2!1svi!2s',
  },
  {
    id: 6,
    images: [
      '/images/landpage/project-4-part-1.jpg',
      '/images/landpage/project-4-part-2.jpg',
      '/images/landpage/project-4-part-3.jpg',
      '/images/landpage/project-4-part-4.jpg',
      '/images/landpage/project-4-part-5.jpg',
      '/images/landpage/project-4-part-6.jpg',
    ],
    status: 'SELLING',
    title: 'Lavita Thuan An',
    timeExprired: '6 tháng',
    profit: 15,
    investors: 0,
    amount: 0,
    total: 1000,
    position: 'TP.Thuận An, T.Bình Dương',
    description: [
      'Sau thành công với chuỗi dự án mang thương hiệu Lavita, Lavita Thuan An là sản phẩm căn hộ tiếp theo của Nhà phát triển dự án Hưng Thịnh Land dành riêng cho cộng đồng trí thức đến từ thành phố thông minh Smart21.',
      'Lavita Thuan An trở thành lựa chọn xứng tầm của các chủ nhân bởi vị trí tọa lạc đắt giá ngay Quốc lộ 13 - một trong những trục giao thông xương sống của các tỉnh thành vùng Kinh tế trọng điểm phía Nam.',
      'Đặc biệt, kết nối vùng thuận tiện của Bình Dương thông qua hệ thống giao thông hoàn thiện, hạ tầng hiện đại, thông thoáng đã góp phần giúp Lavita Thuan An trở thành sự lựa chọn hàng đầu của khách hàng và các nhà đầu tư.',
      'Bên cạnh đó, với vị trí ngay tâm điểm mũi tàu Nguyễn Thị Minh Khai và Quốc lộ 13 cùng nhiều tuyến đường rộng thoáng tỏa đi các hướng, việc di chuyển của cư dân Lavita Thuan An sẽ vô cùng dễ dàng.',
      'Từ đây, cư dân chỉ mất 10 phút để đến Thành phố mới Bình Dương, TP. Thủ Dầu Một, TP. Dĩ An; 20 phút đến TP. Thủ Đức; 25 phút đến TP. Biên Hòa hay 30 phút về Trung tâm TP. HCM.',
    ],
    video: 'H5M32j0Wq3M',
    map: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.9175804631072!2d106.61142291516913!3d10.740835492345663!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f12ad498e93%3A0x443c121080239ca3!2sMOONLIGHT%20CENTRE%20POINT!5e0!3m2!1svi!2s!4v1637741444934!5m2!1svi!2s',
  },
  {
    id: 2,
    images: [
      '/images/landpage/land-2.jpg',
      '/images/landpage/project-1-part-3.jpg',
      '/images/landpage/project-1-part-4.jpg',
      '/images/landpage/project-1-part-5.jpg',
      '/images/landpage/project-1-part-6.jpg',
    ],
    status: 'END',
    title: 'Biệt Thự Phú Mỹ Hưng',
    timeExprired: '6 tháng',
    profit: 50,
    investors: 100,
    amount: 1000,
    total: 1000,
    position: 'Tp. Hồ Chí Minh',
    description: [
      'Vị trí đất và nhà tọa lạc trên địa bàn thị trấn Cần Thạnh, là nơi đông dân cư nhất của Cần Giờ',
      'Khu 50 căn là khu vực an ninh, ổn định và dân trí cao của khu vực, địa điểm dễ tìm, thuận lợi',
      'Vị trí gần UBND huyện (cách 750 m), khu hành chính của huyện, gần UBND thị trấn Cần Thạnh (cách 750 m), kế bên Văn phòng đăng ký đất đai huyện, phòng công chứng, khu vực cán bộ công chức cư ngụ',
      'Đối diện khu thể dục thể thao và trung tâm văn hóa của huyện, mật độ cây xanh và công viên cao nhất khu vực. Thuận tiện giao thông, gần trạm chính xe bus, thuận tiện ra bến tàu cao tốc của các tuyến',
      'Gần trường cấp 1, cấp 2, cấp 3, bệnh viện 500 giường lớn nhất huyện',
      'Theo quy hoạch của Vingroup, đây là khu vực có bãi tắm công cộng, trục đường chính từ UBND huyện đi ra dự án lấn biển. Cách đường chính ra dự án Vingroup 2870ha (chi tiết thêm) chỉ có 500m. Cách đường ven biển của thị trấn 300m',
    ],
  },
  {
    id: 3,
    images: [
      '/images/landpage/land-3.jpg',
      '/images/landpage/project-1-part-3.jpg',
      '/images/landpage/project-1-part-4.jpg',
      '/images/landpage/project-1-part-5.jpg',
      '/images/landpage/project-1-part-6.jpg',
    ],
    status: 'PENDING',
    title: 'Mảnh đất Đồng Nai 500 Heta',
    timeExprired: '6 tháng',
    profit: 50,
    investors: 0,
    amount: 0,
    total: 1000,
    position: 'Đồng Nai',
    description: [
      'Khoảng 20 phút từ khu đô thị Vinhomes Central Park và cầu Thủ Thiêm Quận 2 có thể kết nối nhanh chóng đến Vinhome Quận 9.',
      'Đồng thời, trong tương lai Vành Đai 3 sẽ là tuyến đường huyết mạch chính kết nối dự án Vinhomes Quận 9 với khu vực trung tâm thành phố.',
      'Khu đô thị Vinhomes Grand Park được tập đoàn Vingroup phát triển theo mô hình thành phố thu nhỏ khép kín với hệ sinh thái tiện ích đa dạng, đồng bộ với tiêu chí “ALL IN ONE” đáp ứng cuộc sống trọn vẹn.',
      'Được bình chọn đánh giá là một trong những nơi đáng sống nhất tại Việt Nam, không chỉ mang đến không gian sống trong lành chất lượng với những trải nghiệm tiện ích mới chỉ có tại dự án Vinhomes Grand Park Quận 9.',
      'Mà còn làm “tăng nhiệt” thị trường bất động sản khu Đông TPHCM, mở ra cơ hội đầu tư vô cùng hấp dẫn khi dự án hoàn thiện.',
    ],
    video: 'TRq-khTzUXI',
  },
];

export const DUMMY_PROJECT = DUMMY_PROJECTS[0];

export const DUMMY_PROJECT_IMAGES = [
  '/images/landpage/land-1-part-1.jpg',
  '/images/landpage/land-1-part-2.jpg',
  '/images/landpage/land-1-part-3.jpg',
  '/images/landpage/land-1-part-4.jpg',
  '/images/landpage/land-1-part-4.jpg',
  '/images/landpage/land-1-part-4.jpg',
];

export const DUMMY_SELECT_CITY = [
  { id: 1, name: 'Toàn quốc', value: 'all' },
  { id: 2, name: 'Tp.Hồ Chí Minh', value: 'hcm' },
  { id: 3, name: 'Hà Nội', value: 'hn' },
  { id: 4, name: 'Đà Nẵng', value: 'dn' },
];

export const DUMMY_SELECT_LAND = [
  { id: 1, name: 'Loại nhà đất' },
  { id: 2, name: 'Nhà đất loại 1' },
  { id: 3, name: 'Nhà đất loại 2' },
  { id: 4, name: 'Nhà đất loại 3' },
];

export const TableDummy1 = {
  thead: ['Trạng thái', 'Tổng', 'Tài sản khả dụng', 'Đang đặt lệnh', 'Hành động'],
  tbody: [
    {
      status: 'BNB',
      total: '1,00000000',
      assets: '1,00000000',
      ordering: '0,00000000',
    },
    {
      status: 'BNB',
      total: '1,00000000',
      assets: '1,00000000',
      ordering: '0,00000000',
    },
    {
      status: 'BNB',
      total: '1,00000000',
      assets: '1,00000000',
      ordering: '0,00000000',
    },
    {
      status: 'BNB',
      total: '1,00000000',
      assets: '1,00000000',
      ordering: '0,00000000',
    },
    {
      status: 'BNB',
      total: '1,00000000',
      assets: '1,00000000',
      ordering: '0,00000000',
    },
    {
      status: 'BNB',
      total: '1,00000000',
      assets: '1,00000000',
      ordering: '0,00000000',
    },
    {
      status: 'BNB',
      total: '1,00000000',
      assets: '1,00000000',
      ordering: '0,00000000',
    },
    {
      status: 'BNB',
      total: '1,00000000',
      assets: '1,00000000',
      ordering: '0,00000000',
    },
    {
      status: 'BNB',
      total: '1,00000000',
      assets: '1,00000000',
      ordering: '0,00000000',
    },
    {
      status: 'BNB',
      total: '1,00000000',
      assets: '1,00000000',
      ordering: '0,00000000',
    },
  ],
};

export const TableDummy2 = {
  thead: ['TxHash', 'Địa chỉ gửi', 'Địa chỉ nhận', 'Số lượng', 'Token'],
  tbody: [
    {
      txHash: '0x79b6 ... E841Dd',
      sendAddress: '0x79b6 ... E841Dd',
      getAddress: '0x79b6 ... E841Dd',
      amount: '50,000,000',
      token: 'VNDC',
    },
    {
      txHash: '0x79b6 ... E841Dd',
      sendAddress: '0x79b6 ... E841Dd',
      getAddress: '0x79b6 ... E841Dd',
      amount: '50,000,000',
      token: 'VNDC',
    },
    {
      txHash: '0x79b6 ... E841Dd',
      sendAddress: '0x79b6 ... E841Dd',
      getAddress: '0x79b6 ... E841Dd',
      amount: '50,000,000',
      token: 'VNDC',
    },
    {
      txHash: '0x79b6 ... E841Dd',
      sendAddress: '0x79b6 ... E841Dd',
      getAddress: '0x79b6 ... E841Dd',
      amount: '50,000,000',
      token: 'VNDC',
    },
    {
      txHash: '0x79b6 ... E841Dd',
      sendAddress: '0x79b6 ... E841Dd',
      getAddress: '0x79b6 ... E841Dd',
      amount: '50,000,000',
      token: 'VNDC',
    },
    {
      txHash: '0x79b6 ... E841Dd',
      sendAddress: '0x79b6 ... E841Dd',
      getAddress: '0x79b6 ... E841Dd',
      amount: '50,000,000',
      token: 'VNDC',
    },
    {
      txHash: '0x79b6 ... E841Dd',
      sendAddress: '0x79b6 ... E841Dd',
      getAddress: '0x79b6 ... E841Dd',
      amount: '50,000,000',
      token: 'VNDC',
    },
    {
      txHash: '0x79b6 ... E841Dd',
      sendAddress: '0x79b6 ... E841Dd',
      getAddress: '0x79b6 ... E841Dd',
      amount: '50,000,000',
      token: 'VNDC',
    },
    {
      txHash: '0x79b6 ... E841Dd',
      sendAddress: '0x79b6 ... E841Dd',
      getAddress: '0x79b6 ... E841Dd',
      amount: '50,000,000',
      token: 'VNDC',
    },
    {
      txHash: '0x79b6 ... E841Dd',
      sendAddress: '0x79b6 ... E841Dd',
      getAddress: '0x79b6 ... E841Dd',
      amount: '50,000,000',
      token: 'VNDC',
    },
    {
      txHash: '0x79b6 ... E841Dd',
      sendAddress: '0x79b6 ... E841Dd',
      getAddress: '0x79b6 ... E841Dd',
      amount: '50,000,000',
      token: 'VNDC',
    },
  ],
};

export const DUMMY_PROGRESS_PRICE_STEP = [
  { label: '0.7M VND', className: 'bg-teal-300  ', discount: 90, tokenValue: 10, price: 700000 },
  { label: '1.4M VND', className: 'bg-teal-300  ', discount: 80, tokenValue: 10, price: 1400000 },
  { label: '2.1M VND', className: 'bg-teal-300  ', discount: 70, tokenValue: 10, price: 2100000 },
  { label: '2.1M VND', className: 'bg-teal-300  ', discount: 60, tokenValue: 10, price: 2800000 },
  { label: '2.1M VND', className: 'bg-teal-300  ', discount: 50, tokenValue: 10, price: 3500000 },
  { label: '2.1M VND', className: 'bg-teal-300  ', discount: 40, tokenValue: 50, price: 4200000 },
  { label: '2.1M VND', className: 'bg-teal-300  ', discount: 30, tokenValue: 50, price: 4900000 },
  { label: '2.1M VND', className: 'bg-teal-300  ', discount: 20, tokenValue: 50, price: 5600000 },
  { label: '2.1M VND', className: 'bg-teal-400  ', discount: 10, tokenValue: 50, price: 6300000 },
  { label: '2.1M VND', className: 'bg-teal-500  ', discount: 8, tokenValue: 50, price: 6440000 },
  { label: '2.1M VND', className: 'bg-teal-600  ', discount: 5, tokenValue: 100, price: 6650000 },
  { label: '2.1M VND', className: 'bg-teal-700  ', discount: 3, tokenValue: 100, price: 6790000 },
  { label: '2.1M VND', className: 'bg-teal-800  ', discount: 2, tokenValue: 200, price: 6860000 },
  { label: '2.1M VND', className: 'bg-teal-900', discount: 1, tokenValue: 300, price: 6930000 },
];

export const DUMMY_TOTAL_NEEDED_INVEST = '6794300000';
