export const BANK_LIST = [
  {
    name: 'Ngân hàng thương mại cổ phần An Bình (ABBANK)',
    image: '/images/payment/abbank_logo.png',
    bankCode: 'ABBANK',
  },
  { name: 'Ngân hàng ACB', image: '/images/payment/acb_logo.png', bankCode: 'ACB' },
  { name: 'Ngân hàng Nông nghiệp (Agribank)', image: '/images/payment/agribank_logo.png', bankCode: 'AGRIBANK' },
  { name: 'Ngân Hàng TMCP Bắc Á', image: '/images/payment/bacabank_logo.png', bankCode: 'BACABANK' },
  { name: 'Ngân hàng đầu tư và phát triển Việt Nam (BIDV)', image: '/images/payment/bidv_logo.png', bankCode: 'BIDV' },
  { name: 'Ngân hàng Đông Á (DongABank)', image: '/images/payment/dongabank_logo.png', bankCode: 'DONGABANK' },
  { name: 'Ngân hàng EximBank', image: '/images/payment/eximbank_logo.png', bankCode: 'EXIMBANK' },
  { name: 'Ngân hàng HDBank', image: '/images/payment/hdbank_logo.png', bankCode: 'HDBANK' },
  { name: 'Ngân hàng TNHH Indovina (IVB)', image: '/images/payment/ivb_logo.png', bankCode: 'IVB' },
  { name: 'Ngân hàng thương mại cổ phần Quân đội', image: '/images/payment/mbbank_logo.png', bankCode: 'MBBANK' },
  { name: 'Ngân hàng Nam Á (NamABank)', image: '/images/payment/namabank_logo.png', bankCode: 'NAMABANK' },
  { name: 'Ngân hàng Phương Đông (OCB)', image: '/images/payment/ocb_logo.png', bankCode: 'OCB' },
  { name: 'Ngân hàng Đại Dương (OceanBank)', image: '/images/payment/ojb_logo.png', bankCode: 'OJB' },
  { name: 'Ngân hàng TMCP Đại Chúng Việt Nam', image: '/images/payment/PVComBank_logo.png', bankCode: 'PVCOMBANK' },
  {
    name: 'Ngân hàng TMCP Sài Gòn Thương Tín (SacomBank)',
    image: '/images/payment/sacombank_logo.png',
    bankCode: 'SACOMBANK',
  },
  {
    name: 'Ngân hàng thương mại cổ phần Sài Gòn Công Thương',
    image: '/images/payment/saigonbank.png',
    bankCode: 'SAIGONBANK',
  },
  { name: 'Ngân hàng TMCP Sài Gòn (SCB)', image: '/images/payment/scb_logo.png', bankCode: 'SCB' },
  {
    name: 'Ngân hàng Thương mại cổ phần Sài Gòn - Hà Nội(SHB)',
    image: '/images/payment/shb_logo.png',
    bankCode: 'SHB',
  },
  {
    name: 'Ngân hàng Kỹ thương Việt Nam (TechcomBank)',
    image: '/images/payment/techcombank_logo.png',
    bankCode: 'TECHCOMBANK',
  },
  { name: 'Ngân hàng Tiên Phong (TPBank)', image: '/images/payment/tpbank_logo.png', bankCode: 'TPBANK' },
  { name: 'Ngân hàng Việt Nam Thịnh vượng (VPBank)', image: '/images/payment/vpbank_logo.png', bankCode: 'VPBANK' },
  { name: 'Ngân Hàng TMCP Đông Nam Á', image: '/images/payment/seabank_logo.png', bankCode: 'SEABANK' },
  {
    name: 'Ngân hàng Thương mại cổ phần Quốc tế Việt Nam (VIB)',
    image: '/images/payment/vib_logo.png',
    bankCode: 'VIB',
  },
  { name: 'Ngân hàng TMCP Việt Á', image: '/images/payment/vietabank_logo.png', bankCode: 'VIETABANK' },
  {
    name: 'Ngân hàng thương mại cổ phần Việt Nam Thương Tín',
    image: '/images/payment/vietbank_logo.png',
    bankCode: 'VIETBANK',
  },
  { name: 'Ngân Hàng Bản Việt', image: '/images/payment/vccb_logo.png', bankCode: 'VIETCAPITALBANK' },
  {
    name: 'Ngân hàng Ngoại thương (Vietcombank)',
    image: '/images/payment/vietcombank_logo.png',
    bankCode: 'VIETCOMBANK',
  },
  { name: 'Ngân hàng Công thương (Vietinbank)', image: '/images/payment/vietinbank_logo.png', bankCode: 'VIETINBANK' },
  { name: 'Ngân Hàng BIDC', image: '/images/payment/bidc_logo.png', bankCode: 'BIDC' },
  { name: 'NGÂN HÀNG LIÊN DOANH LÀO - VIỆT', image: '/images/payment/laovietbank_logo.png', bankCode: 'LAOVIETBANK' },
  { name: 'Ngân hàng TNHH MTV Woori Việt Nam', image: '/images/payment/woori_logo.png', bankCode: 'WOORIBANK' },
  { name: 'Ngân hàng Quốc dân (NCB)', image: '/images/payment/ncb_logo.png', bankCode: 'NCB' },
];

export const VISA_MASTER = [
  { name: 'Thẻ quốc tế Visa', image: '/images/payment/visa_logo.png', bankCode: 'VISA' },
  { name: 'Thẻ quốc tế MasterCard', image: '/images/payment/mastercard_logo.png', bankCode: 'MASTERCARD' },
  // {name: 'Thẻ quốc tế JCB', image: '/images/payment/jcb_logo.png', bankCode: 'JCB'},
  // {name: 'American Express', image: '/images/payment/amex_logo.png', bankCode: 'AMEX'},
  // {name: 'UnionPay International', image: '/images/payment/amex_logo.png', bankCode: 'UPI'},
];

export const VN_PAY_RESPONSE_CODE_STATUS = {
  '00': 'Thanh toán thành công',
  '07': 'Trừ tiền thành công',
  '09': 'Thanh toán không thành công',
  10: 'Thanh toán không thành công',
  11: 'Thanh toán không thành công',
  12: 'Thanh toán không thành công',
  13: 'Thanh toán không thành công',
  24: 'Thanh toán không thành công',
  51: 'Thanh toán không thành công',
  65: 'Thanh toán không thành công',
  75: 'Thanh toán không thành công',
  79: 'Thanh toán không thành công',
  99: 'Thanh toán không thành công',
};
export const VN_PAY_RESPONSE_CODE_MESSAGE = {
  '07': 'Lý do: Giao dịch bị nghi ngờ (liên quan tới lừa đảo, giao dịch bất thường).',
  '09': 'Lý do: Thẻ/Tài khoản của khách hàng chưa đăng ký dịch vụ InternetBanking tại ngân hàng.',
  10: 'Lý do: Khách hàng xác thực thông tin thẻ/tài khoản không đúng quá 3 lần',
  11: 'Lý do: Đã hết hạn chờ thanh toán. Xin quý khách vui lòng thực hiện lại giao dịch.',
  12: 'Lý do: Thẻ/Tài khoản của khách hàng bị khóa.',
  13: 'Lý do: Quý khách nhập sai mật khẩu xác thực giao dịch (OTP). Xin quý khách vui lòng thực hiện lại giao dịch.',
  24: 'Lý do: Khách hàng hủy giao dịch',
  51: 'Lý do: Tài khoản của quý khách không đủ số dư để thực hiện giao dịch.',
  65: 'Lý do: Tài khoản của Quý khách đã vượt quá hạn mức giao dịch trong ngày.',
  75: 'Lý do: Ngân hàng thanh toán đang bảo trì.',
  79: 'Lý do: KH nhập sai mật khẩu thanh toán quá số lần quy định. Xin quý khách vui lòng thực hiện lại giao dịch',
  99: 'Lý do: Các lỗi khác (lỗi còn lại, không có trong danh sách mã lỗi đã liệt kê)',
};

export const VN_PAY_COMMAND_QUERYDR_STATUS = {
  '02': 'Merchant không hợp lệ (kiểm tra lại vnp_TmnCode)',
  '03': 'Dữ liệu gửi sang không đúng định dạng',
  91: 'Không tìm thấy giao dịch yêu cầu',
  94: 'Yêu cầu bị trùng lặp trong thời gian giới hạn của API (Giới hạn trong 5 phút)',
  97: 'Chữ ký không hợp lệ',
  99: 'Các lỗi khác (lỗi còn lại, không có trong danh sách mã lỗi đã liệt kê)',
};

export const VN_PAY_COMMAND_REFUND_STATUS = {
  '02': 'Tổng số tiền hoản trả lớn hơn số tiền gốc',
  '03': 'Dữ liệu gửi sang không đúng định dạng',
  '04': 'Không cho phép hoàn trả toàn phần sau khi hoàn trả một phần',
  13: 'Chỉ cho phép hoàn trả một phần',
  91: 'Không tìm thấy giao dịch yêu cầu hoàn trả',
  93: 'Số tiền hoàn trả không hợp lệ. Số tiền hoàn trả phải nhỏ hơn hoặc bằng số tiền thanh toán.',
  94: 'Yêu cầu bị trùng lặp trong thời gian giới hạn của API (Giới hạn trong 5 phút)',
  95: 'Giao dịch này không thành công bên VNPAY. VNPAY từ chối xử lý yêu cầu.',
  97: 'Chữ ký không hợp lệ',
  98: 'Timeout Exception',
  99: 'Các lỗi khác (lỗi còn lại, không có trong danh sách mã lỗi đã liệt kê)',
};

export const PAYMENT_HISTORY_STATUS = {
  NEW: 'Chờ xử lý',
  ACTIVE: 'Đang mở',
  INACTIVE: 'Đã tắt',
  SUCCESS: 'Thành công',
  FAIL: 'Thất bại',
};

// -----------------
// MOMO
export const MOMO_RESPONSE_CODE_STATUS = {
  0: 'Giao dịch thành công',
  9000: 'Giao dịch đã được xác nhận thành công',
  8000: 'Giao dịch đang ở trạng thái cần được người dùng xác nhận thanh toán lại',
  7000: 'Giao dịch đang được xử lý',
  1000: 'Giao dịch đã được khởi tạo, chờ người dùng xác nhận thanh toán',
  11: 'Truy cập bị từ chối',
  12: 'Phiên bản API không được hỗ trợ cho yêu cầu này',
  13: 'Xác thực doanh nghiệp thất bại',
  20: 'Yêu cầu sai định dạng',
  21: 'Số tiền giao dịch không hợp lệ',
  40: 'RequestId bị trùng',
  41: 'OrderId bị trùng',
  42: 'OrderId không hợp lệ hoặc không được tìm thấy',
  43: 'Yêu cầu bị từ chối vì xung đột trong quá trình xử lý giao dịch',
  1001: 'Giao dịch thanh toán thất bại do tài khoản người dùng không đủ tiền',
  1002: 'Giao dịch bị từ chối do nhà phát hành tài khoản thanh toán',
  1003: 'Giao dịch bị đã bị hủy',
  1004: 'Giao dịch thất bại do số tiền thanh toán vượt quá hạn mức thanh toán của người dùng',
  1005: 'Giao dịch thất bại do url hoặc QR code đã hết hạn',
  1006: 'Giao dịch thất bại do người dùng đã từ chối xác nhận thanh toán',
  1007: 'Giao dịch bị từ chối vì tài khoản người dùng đang ở trạng thái tạm khóa',
  1026: 'Giao dịch bị hạn chế theo thể lệ chương trình khuyến mãi',
  1080: 'Giao dịch hoàn tiền bị từ chối. Giao dịch thanh toán ban đầu không được tìm thấy',
  1081: 'Giao dịch hoàn tiền bị từ chối. Giao dịch thanh toán ban đầu có thể đã được hoàn',
  2001: 'Giao dịch thất bại do sai thông tin liên kết',
  2007: 'Giao dịch thất bại do liên kết hiện đang bị tạm khóa',
  3001: 'Liên kết thất bại do người dùng từ chối xác nhận',
  3002: 'Liên kết bị từ chối do không thỏa quy tắc liên kết',
  3003: 'Hủy liên kết bị từ chối do đã vượt quá số lần hủy',
  3004: 'Liên kết này không thể hủy do có giao dịch đang chờ xử lý',
  4001: 'Giao dịch bị hạn chế do người dùng chưa hoàn tất xác thực tài khoản',
  4010: 'Quá trình xác minh OTP thất bại',
  4011: 'OTP chưa được gửi hoặc hết hạn',
  4100: 'Giao dịch thất bại do người dùng không đăng nhập thành công',
  4015: 'Quá trình xác minh 3DS thất bại',
  10: 'Hệ thống đang được bảo trì',
  99: 'Lỗi không xác định',
};

export const MOMO_RESPONSE_CODE_MESSAGE = {
  9000: 'Đối với thanh toán 1 bước (autoCapture=1), đây có thể xem như giao dịch thanh toán đã thành công. Đối với thanh toán 2 bước (autoCapture=0), vui lòng thực hiện tiếp yêu cầu capture hoặc cancel. Đối với liên kết. vui lòng tiến hành yêu cầu lấy recurring token. with either capture or cancel request. For binding, please proceed to request the recurring token.',
  8000: 'Giao vẫn đang chờ người dùng xác nhận thanh toán; trạng thái của giao dịch sẽ được tự động thay đổi ngay sau khi người dùng xác nhận hoặc hủy thanh toán.',
  7000: 'Vui lòng chờ giao dịch được xử lý hoàn tất.',
  1000: 'Giao vẫn đang chờ người dùng xác nhận thanh toán; trạng thái của giao dịch sẽ được tự động thay đổi ngay sau khi người dùng xác nhận hoặc hủy thanh toán.',
  11: 'Cấu hình tài khoản doanh nghiệp không cho phép truy cập. Vui lòng xem lại các thông tin đăng ký và cấu hình trên M4B, hoặc liên hệ trực tiếp với MoMo để được điều chỉnh.',
  12: 'Vui lòng nâng cấp lên phiên bản mới nhất của cổng thanh vì, vì phiên bản bạn đang truy cấp hiện không còn được hỗ trợ.',
  13: 'Vui lòng kiểm tra thông tin kết nối, bao gồm cả chữ ký mà bạn đang sử dụng, và đối chiếu với các thông tin được cung cấp từ M4B.',
  20: 'Vui lòng kiểm tra định dạng của yêu cầu, các biến thể, hoặc tham số còn thiếu.',
  21: 'Vui lòng kiểm tra nếu số tiền thanh toán nằm trong giới hạn quy định của yêu cầu thanh toán này. Đối với yêu cầu dạng capture, hãy kiểm tra số tiền capture có bằng với số tiền đã được xác nhận trước đó hay không.',
  40: 'Vui lòng thử lại với một requestId khác.',
  41: 'Vui lòng truy vấn trạng thái của orderId này, hoặc thử lại với một orderId khác.',
  42: 'Vui lòng thử lại với một orderId khác.',
  43: 'Trước khi thử lại, vui lòng kiểm tra nếu có một giao dịch khác đang được xử lý có thể hạn chế yêu cầu này được tiếp nhận, hoặc orderId được sử dụng không phù hợp với yêu cầu này.',
  1002: 'Sự từ chối xảy ra khi thẻ được dùng để thanh toán hiện không còn khả dụng, hoặc kết nối đến hệ thống của nhà phát hành thẻ bị gián đoạn. Vui lòng tạm thời sử dụng phương thức thanh toán khác.',
  1003: 'Giao dịch bị hủy bởi doanh nghiệp hoặc bởi trình xử lý timeout của MoMo. Vui lòng đánh dấu giao dịch này đã bị hủy (giao dịch thất bại).',
  1004: 'Vui lòng đánh dấu giao dịch này thất bại, và thử lại vào một khoảng thời gian khác.',
  1005: 'Vui lòng gửi lại một yêu cầu thanh toán khác.',
  1006: 'Vui lòng gửi lại một yêu cầu thanh toán khác.',
  1007: 'Vui lòng sử dụng một phương thức thanh toán khác không bị ràng buộc với tài khoản người dùng này. Đối với giao dịch, bạn có thể liên hệ với MoMo để được giúp đỡ.',
  1026: 'Vui lòng liên hệ MoMo để biết thêm chi tiết.',
  1080: 'Vui lòng kiểm tra nếu orderId hoặc TID được dùng trong yêu cầu này là chính xác.',
  1081: 'Vui lòng kiểm tra nếu giao dịch thanh toán ban đầu đã được hoàn thành công, hoặc số tiền hoàn vượt quá số tiền cho phép hoàn của giao dịch thanh toán ban đầu.',
  2001: 'Token liên kết không tồn tại hoặc đã bị xóa, vui lòng cập nhật dữ liệu của bạn.',
  2007: 'Token liên kết hiện đang ở trạng thái không hoạt động, do người dùng đã chủ động tạm khóa liên kết.',
  3002: 'Từ chối này thường xảy ra khi partnerClientId dùng trong yêu cầu đã được liên kết với một hoặc nhiều tài khoản MoMo trước đó. Vui lòng liên hệ MoMo để biết thêm chi tiết.',
  3003: 'Vui lòng liên hệ MoMo để biết thêm chi tiết.',
  3004: 'Vui lòng kiểm tra nếu có bất kỳ giao dịch chờ liên quan đén token này chưa được yêu cầu capture hoặc cancel (hủy).',
  4010: 'Quá trình xác minh người dùng thất bại. Vui lòng gửi một yêu cầu xác minh người dùng khác để thử lại.',
  4011: 'Vui lòng yêu cầu gửi một mã OTP khác.',
  4015: 'Quá trình xác minh người dùng thất bại. Vui lòng gửi một yêu cầu xác minh người dùng khác để thử lại.',
  10: 'Vui lòng quay lại sau khi bảo trì được hoàn tất.',
  99: 'Vui lòng liên hệ MoMo để biết thêm chi tiết.',
};
// ----------------
// PAYME
export const PAYME_RESPONSE_STATUS = {
  success: 'Thanh toán PayME thành công',
  fail: 'Thanh toán PayME thất bại',
};
